### ISSUE TITLE
Translation files from Kinvey not being used after download

### ISSUE THREAD

**Issue by bradmartin** [PushTracker/EvalApp#103]

**Comment by finger563** [comment]
might be android too

**Comment by bradmartin** [comment]
Gonna make some notes as I go about this here:

- File is downloading (good)
- Can read the file after it's been downloaded and saved and it matches the file that is uploaded to Kinvey 👍 (good)

I think the issue is that our `TranslateLoader` wires up all the local files in the app.module when the app is initialized. Currently testing a few things there to confirm.
