### ISSUE TITLE
UX handling for language setting in account

### ISSUE THREAD

**Issue by bradmartin** [PushTracker/EvalApp#105]
@finger563 - right now the dropdown for languages in account.component changes the set language in the translation, however just changing that doesn't send off to Kinvey to update the account.

Do we want to make them tap `Save` to change the language? Likely better option, as opposed to POST-ing to Kinvey each time the toggle changes or is opened/closed due to possible mistakes.

Trade offs either way.

**Comment by finger563** [comment]
Yea i think having it by default save into the account when they change it is fine - and maybe we should just save on navigating away from the page anyway

**Comment by bradmartin** [comment]
Got it wired up to save to Kinvey when it's changed without a prompt and then the `SAVE` button is still intact 👍
