### ISSUE TITLE
Update "Smart Evaluation" on Splash Screen

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#132]
Splash Screen text doesn't have good formatting - will need to regenerate the images sadly

**Comment by finger563** [comment]
@devondoebele or @ken-max which one of you has the source file for the splash screen?

**Comment by finger563** [comment]
maybe it's ok? seems to just be me looking at it and thinking it looks weird :man_shrugging:

**Comment by finger563** [comment]
So I think we're good here? @bradmartin @devondoebele weigh in and let me know if we're still working on this or we think that it's good enough for release

**Comment by devondoebele** [comment]
I need to run Android to see if they are the same.

Devon Doebele
Permobil, Inc.
321.288.4066
devon.doebele@permobil.com

**Comment by bradmartin** [comment]
Android splash: https://github.com/PushTracker/EvalApp/blob/master/maxmobility/apps/eval-mobile/app/App_Resources/Android/src/main/res/drawable-xxxhdpi/logo.png

iOS: https://github.com/PushTracker/EvalApp/blob/master/maxmobility/apps/eval-mobile/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default%402x.png

**Comment by finger563** [comment]
Closing as I think we're fine with it as is.
