### ISSUE TITLE
Translation functionality

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#14]
Support for multiple languages using [ngx-translate](http://www.ngx-translate.com/)
[See this link for reference](http://www.ngx-translate.com/)

## languages needed for translation
- [x] English
- [x] French
- [x] German
- [x] Dutch
- [x] Spanish

## translation related functionality
- [ ] Support for Translating items from Kinvey (#46) (https://github.com/ngx-translate/http-loader)
- [ ] Ensure items like ota status, dialogs / prompts, etc. (english in code) is traslated
- [ ] ota features (downloaded as metadata in ota files from kinvey datastore)

## pages that need translation
- [x] OTA
- [ ] demo detail 
- [x] eval entry
- [x] training

**Comment by bradmartin** [comment]
close via https://github.com/PushTracker/EvalApp/commit/cd694d53ec6b0c4fe296d3afa5044bb80abad200 

will split out some of the remaining work into new issues
