### ISSUE TITLE
Demo unit images don't save

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#144]
Images takin for demo unit don't persist between restarts of the app.

**Comment by bradmartin** [comment]
Working through this on branch issue-144.

Findings so far:
When saving the demo unit the image value is not stored in the array for the object so it makes sense that the images aren't restoring when viewing the demos after saving the picture of the PT/SD.

Some progress made on the branch to track the debugging efforts so far. Simplifying some of the execution flow right now to finalize the image value being saved correctly and then also being restored and converted to an ImageSource so we can load it on the `Image` when the page loads.

**Comment by bradmartin** [comment]
Dont run that branch yet, I'll refactor some stuff to make it work. Image logic is fine it's just not saving to the demo units locally so when the binding is refreshed with the demo from the array it's null so you get the stock images.
