### ISSUE TITLE
PushTracker OTA paused when app is backgrounded

### ISSUE THREAD

**Issue by guo-max** [PushTracker/EvalApp#154]
Our current PT App will still OTA at a lower data rate.

**Comment by finger563** [comment]
One option (if we can't easily / quickly make it so that it works while backgrounded) is to make the screen not turn off during OTA (since phone locking / screen shutting off also pauses the ota).

**Comment by bradmartin** [comment]
Closed via https://github.com/PushTracker/EvalApp/commit/ea0194c409ea106919d6957d6fc70a33a073379c
