### ISSUE TITLE
OTA Page Implementation and Use Cases

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#17]
For the OTA page, we need to handle the following considerations:

  - [x] Users are not connected to a SmartDrive
  - [x]  Users are not connected to a PushTracker
  - [x]  More than one SmartDrive is available (when scanning)
  - [x]  More than one PushTracker has connected
  - [x]  The user is connected to a PushTracker or SmartDrive which is already the most up to date version - we should prompt to ask if the user would like to force OTA the device
  - [x]  The user would like to cancel the OTA
  - [x]  The user is waiting for the OTA to complete - we should show the progress bars (possibly more than one at a time depending on device / ota) 
  - [x]  The user is waiting for the OTA to complete - we should show some relevant feature information ("new in this release" or "did you know?"
  - [x]  Downloading the OTA data and description / features from the server

**Comment by finger563** [comment]
Realistically, we will probably want the `OTA` function to be a function of either the _device_, e.g. the `PushTracker` or `SmartDrive` class (that doesn't exist yet) or the `bluetooth.service`, where the OTA function takes arguments of the form:
```js
{
    "device": <uuid or direct device reference>,
    "timeout": <seconds>,
    "otaData": <buffer containing ota data>, // only if this is a part of the bluetooth.service, otherwise omitted
    "timeoutCallback": function() {
    },
    "progressCallback": function(progress: number) {
    },
    "completeCallback": function() {
    },
    "failureCallback": function(error) {
    }
}
```

**Comment by finger563** [comment]
Once we have that, then we can more easily re-use the code across apps and the OTA page simply becomes UI with some hooks into the bluetooth code.

**Comment by finger563** [comment]
@bradmartin @devondoebele if you have any suggestions for this API, please post them here - what I posted above is merely a rough sketch of how we might move forward and will definitely need expansion (and possibly scrapping in favor of a better API ;) )

**Comment by finger563** [comment]
### OTA Process for PushTracker
---
0. PushTracker is connected to the App since App cannot initiate connection to PT
1. App sends a packet with the format:
    ```
    Type: Command
    SubType: StartOTA
    otaDevice: Comm::Packet::OTA::PushTracker
    ```
2. App waits for packet with the format:
    ```
    Type: Command
    SubType: OTAReady
    ```
    and periodically continues sending `StartOTA` packet as long as it hasn't received `OTAReady` and there is a connection.
3. App chunks the `OTA Data` into *16 byte chunks* and sends them sequentially into packets of the form:
    ```
    Type: OTA
    SubType: Comm::Packet::OTA::PushTracker
    bytes: <16 byte firmware chunk>
    ```
4. Once app has sent all the bytes of the `OTA Data`, it sends a packet of the form:
    ```
    Type: Command
    SubType: StopOTA
    otaDevice: Comm::Packet::OTA::PushTracker
    ```
    at which point the PushTracker will reset (which will terminate the bluetooth connection)
5.  The app should display information to the user telling them to re-pair the PushTracker to the app
6. When the PushTracker is re-paired, the app should tell the user to re-connect the PushTracker to the app
7. When the PushTracker is re-connected, the app should check the `VersionInfo` from the PushTracker to see if the update succeeded and inform the user accordingly.

### OTA Process for SmartDrive and SmartDrive Bluetooth
---
0. SmartDrive is on but not currently connected to the PushTracker or any other phone / app.
1. App sends a packet with the format:
    ```
    Type: Command
    SubType: StartOTA
    otaDevice: Comm::Packet::OTA::SmartDrive / Comm::Packet::OTA::SmartDriveBluetooth
    ```
    *Note:* if sending to the `SmartDrive`, the smartdrive will reboot, terminating the connection - the app will need to handle the re-connection of the SmartDrive and then proceed with step 2.
2. App waits for packet with the format:
    ```
    Type: Command
    SubType: OTAReady
    ```
    and periodically continues sending `StartOTA` packet as long as it hasn't received `OTAReady` and there is a connection.
3. App chunks the `OTA Data` into *16 byte chunks* and sends them sequentially into packets of the form:
    ```
    Type: OTA
    SubType: Comm::Packet::OTA::PushTracker
    bytes: <16 byte firmware chunk>
    ```
4. Once app has sent all the bytes of the `OTA Data`, it sends a packet of the form:
    ```
    Type: Command
    SubType: StopOTA
    otaDevice: Comm::Packet::OTA::SmartDrive / Comm::Packet::OTA::SmartDriveBluetooth
    ```
    at which point the SmartDrive will reset (which will terminate the bluetooth connection) - the app will need to scan again for the SmartDrive (with the same MAC Address) and try to connect / subscribe again to it before proceeding with step 5.
5. When the SmartDrive is re-connected, the app should check the `DeviceInfo` for the `SmartDriveBluetooth` or the `MotorInfo::version` for the `SmartDrive` to see if the update succeeded and inform the user accordingly.

**Comment by finger563** [comment]
As a note - we've had some discussions internally about how we could merge some of these processes together to make them a little simpler and less error-prone for the user - discussions related to that will come next week; all of the steps will still exist we will just rearrange them so that we don't have to re-do certain steps :)

**Comment by guo-max** [comment]
Step 3 and 4 for OTA SDBT need be updated.

**Comment by finger563** [comment]
right now almost all concerns are implemented - we just need

- [ ] a better display of the features of the new firmware / tips & tricks

**Comment by finger563** [comment]
Now that the features / tips / tricks are pulled from the server this is done
