### ISSUE TITLE
Push Notifications stop working in certain scenarios

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#174]
### iOS
Note: in both of the scenarios below - if the user closes the app and re-opens it, push notifications will work again
- [x] user logs out and logs back in
- [x] user navigates to account page and then back to the app

**Comment by bradmartin** [comment]
Related: https://github.com/Kinvey/nativescript-sdk/issues/44

**Comment by bradmartin** [comment]
Tested both scenarios and all is good.
