### ISSUE TITLE
Add UI for "trial failure"

### ISSUE THREAD

**Issue by devondoebele** [PushTracker/EvalApp#181]
If a user cannot complete the trial, we need to be able to document it.

**Comment by bradmartin** [comment]
Have tested and improved following:

- UI/UX exists for scenarios of push trackers connected and confirming versions.
- Timeout for starting/stopping trial
- When trial WITH SMARTDRIVE start/stop fails an alert should be shown.

I think we're good to close this one now, if we need specific event handling we can open a new issue with specifics of what/how to throw the events 👍
