### ISSUE TITLE
Add ability to resume evaluation

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#190]
Right now the user might accidentally leave the evaluation before it is saved in kinvey.  It would be good to allow them to resume the evaluation - and warn them if they have an unfinished evaluation when starting a new one.

**Comment by bradmartin** [comment]
About 50% on this one. Need to make sure the logic flows correctly. 

The confirmation to resume working on a previous eval is there but it's not restoring the data. Should be a quick fix to just make sure the evaluation item is set to the data on the service, will try to finish tomorrow.
