### ISSUE TITLE
Imrove UI / UX for demo unit detail page / demo unit list page

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#196]
Right now it's not clear how to update where a demo unit is (you have to press `Save`) and there is no indication that it has been updated. We need to update this UI and also prepare for a adding UI for requesting, releasing, and returning demo units

We need:
- [x] a geolocation button on the demo details page that asks for confirmation if they want to update the location of the demo unit to be the current location (and tell them what it is)
- [x] a similar button with similar functionality on the demo list page
- [x] buttons on the demo list page for 1. handing over a demo unit to a clinician, 2. retrieving a demo unit from a clinician, and 3. requesting a demo unit from nearby reps
- [x] change styling of demo unit if you are the `owner` of it. The owner is updated during handoff/retrieval. When unit is created, the REP is the OWNER until it's changed to a clinician. The rep will enter the Clinician's EMAIL to confirm the hand off.

**Comment by bradmartin** [comment]
Endpoint is 90% done. Need to update the demo owner_id and it'll be functioning completely for now. Outside of the scope of sending geolocated push/emails to reps for demo requests.

**Comment by bradmartin** [comment]
Will finish off the list styling, demo update, and location in demo-details now which will close out this issue. Then have a release go out.
