### ISSUE TITLE
Push Notification Icon in notification area only shows red box

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#197]

**Comment by bradmartin** [comment]
When the icon is provided for notifications (mentioned in slack yesterday) this won't be an issue. 
We'll set these tags in the manfiest:

``` 
    <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/logo" />
    <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/permobil_blue" />

```

a transparent icon (typically what most apps use) for notifications would ignore the background coloring in the notification panel on android.

**Comment by bradmartin** [comment]
![icon-final white-transparent](https://user-images.githubusercontent.com/6006148/46957996-76985c80-d05e-11e8-8de2-9f26b23de09a.png)
![icon-final white](https://user-images.githubusercontent.com/6006148/46958004-78fab680-d05e-11e8-826d-06a4ac44e3cc.png)
