### ISSUE TITLE
Update styling / layout for PushTracker Settings page

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#230]
Few things:
- [x] right now there is no way to directly enter the pushtracker settings page or even know it's there - we need to add it to the main page
- [x] Some settings aren't exposed on the page
- [x] The styling of the page is inconsistent w.r.t. the rest of the app
- [x] There is no icon for the page (or for the shortcut on the main page)

**Comment by bradmartin** [comment]
![pt-gear](https://user-images.githubusercontent.com/6006148/46964949-0c3be800-d06f-11e8-88f0-955697b169bb.png)

**Comment by bradmartin** [comment]
Note: possibly switch all the images back to transparent background so we can load any background during the image update since they're too low res right now

**Comment by finger563** [comment]
Now that we have this icon, this issue is CLOSED :)
