### ISSUE TITLE
Demo RLV layout items shifted randomly

### ISSUE THREAD

**Issue by bradmartin** [PushTracker/EvalApp#249]
![screenshot_20181015-170655](https://user-images.githubusercontent.com/6006148/46981258-37d5c700-d09d-11e8-8761-9e932c4b74b6.png)
![screenshot_20181015-170652](https://user-images.githubusercontent.com/6006148/46981260-37d5c700-d09d-11e8-8682-5e5676d5801d.png)

Per William: 

```
it doesn't do it on the first entry, only the last
only when i scroll does it affect the first entry
it has to do with off-screen items
only once i scroll the first element off screen does it get affected
and the last is affected because initially it's the only one off screen
```

**Comment by finger563** [comment]
on ios they are all shifted, not just off-screen ones
