### ISSUE TITLE
NativeScript IQKeyboardManager Plugin not working with Angular

### ISSUE THREAD

**Issue by devondoebele** [PushTracker/EvalApp#26]

**Comment by bradmartin** [comment]
![iqkeyboard](https://user-images.githubusercontent.com/6006148/38146491-dc44bfde-3413-11e8-9aa7-06848431aae7.png)

If you notice the bar above the keyboard, that's it. Added the dep and confirmed all to be working.

Let me know if you have any issues with it though or if you want to customize it any, we can write something for that later on.
