### ISSUE TITLE
Need to tell the user to have the PushTracker connected to the SmartDrive when starting trial

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#260]
We should check the `distance` received from the pushtracker to ensure that it is not 0, and we should tell the user before connecting that they should have the SmartDrive connected to the PushTracker to ensure it has the latest distance information.

**Comment by bradmartin** [comment]
@finger563 - is the pushtracker snackbar here telling them to connect a PT enough or no?

**Comment by finger563** [comment]
Yeah we need to check to make sure distance is non-zero and we probably need to make sure it's different from the start when they stop the trial
