### ISSUE TITLE
Add checks to snackbars and such

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#262]
Right now if a snackbar comes up on a delay and the user has navigated away from the page before the snackbar delay fired, the app will crash once the snackbar tries to fire from the timeout.  Need to cancel the timers on navigating away to prevent snackbar and such from showing.  

Alternative is to ensure either A) the user can't navigate away if we want to show them data, or B) the snackbar is a service which may help it maintain its lifecycle and view attachment

**Comment by bradmartin** [comment]
B should work

**Comment by finger563** [comment]
Yea - I've checked the fancy-alerts from the FAQs and they don't seem to care at all if you navigate before / during / after they display so that's good news

**Comment by bradmartin** [comment]
I'm guessing the crash was the snackbar trying to grab the topmost.frame on android 🤔

**Comment by bradmartin** [comment]
Ran some tests on snackbar to see if service would work and it will also fail. It's the snackbar API that requires it to have a valid `View` to attach to. Right now it's attached to the NS frame (main view). I tried creating the snackbar on the android `DecorView` and `RootView` which works since those are android `View` instances, but it's not a good approach. The snackbar ends up overlaying the navigation bar and it's not legible in areas due to nav buttons.

The frame isn't available during navigation, even in android projects that nav to different activities.

So the simplest and likely better option is to move from the snackbar for those non blocking notices to the feedback plugin since it's being attached to the `DecorView` and it looks good in doing so 👍

**Comment by bradmartin** [comment]
https://github.com/PushTracker/EvalApp/commit/c87185a861e0d1243e02067df48f273ad4e94e69 addresses several areas.

We need to unify on the UX here.

Maybe:
- Use toast for non-blocking simple messages.
- Use feedback for a higher importance notification, still non-blocking.
- Use alerts for blocking

**Comment by finger563** [comment]
Yeah I think that solution is the best approach since it unifies the UI and solves the crash

**Comment by finger563** [comment]
Does toast or fancy alert support actions?

**Comment by finger563** [comment]
E.g. the `more info` from the trial page

**Comment by bradmartin** [comment]
Toast has no actions, so no bueno with it. So only short messages work best.

**Comment by bradmartin** [comment]
CFAlert supports actions for blocking prompts 👍 - so can change the snackbar action there with those if you prefer

**Comment by bradmartin** [comment]
@finger563 - just so we have clear direction here.

We only have the snackbar on pairing, trial and bluetooth.service, which will show based on some interaction/event. So I think we're safe on not having it throw an exception with our current usage.

It probably shouldn't live in the bluetooth service and we should handle it in the component but that can be held off for some refactoring/clean up later date.

**Comment by bradmartin** [comment]
With all the said...

How do you want to unify the alerts, prompts, etc. across the app? 

Do you want to stick with the `nativescript-feedback` plugin that we use on the FAQs on home.component right now for `non-blocking`. This would include replacing the snackbars.

Using the `toast` for simple quick messages such as `Demo request successful.`

Using the built in native `alert` for **blocking** dialogs so the user has to interact.

**Comment by bradmartin** [comment]
I've removed CFAlert plugin. This will help us unify on the UX with alert type events.

Using blocking dialogs when necessary
Using `feedback` plugin for non blocking messages that aren't critical to user
Using snackbar & toast for non blocking short messages - like `Eval saved.`
