### ISSUE TITLE
Stub out data structures and interfaces

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#3]
First Class Objects:
* User
  * email
  * name
  * phone number
  * region
  * associated SDs
* SD
  * serial number(s)
  * trials
  * location history
  * associated users
  * settings
* Trial
  * time information (with / without / training / etc.)
  * SD associated
  * user associated?

**Comment by finger563** [comment]
User Functions:
 * End User
   * Responds to questionnaires about pain / fatigue / activity
   * Trains on how to use SmartDrive (with clinician and on their own)
 * Clinician / ATP
   * Registers use of Dealer's / Rep's SmartDrive
   * Trains users on how to use SmartDrive
   * Trains self on how to use SmartDrive
   * Trains self on how to perform SmartDrive evaluation with user
   * Performs full evaluation of SmartDrive with user
   * Generates LMN for user based on evaluation data
   * Performs OTA for SmartDrive
 * Dealer / Rep
   * Registers ownership of multiple SmartDrives
   * Tracks location and use of SmartDrives (and can see their usage history and resultant clinical data)
   * Performs OTA for SmartDrive
   * Trains self on how to use SmartDrive

User Data: 
 * End User:
   * Email
   * Name
   * Date of Birth
   * Injury Level
   * Chair Type
   * Chair Setup
   * Questionnaire data (multiple days):
     * Fatigue level
     * Pain Level
     * Activity Level
     * Enjoyment of SmartDrive
 * Clinician / ATP:
   * Email
   * Name
   * Phone Number
   * Evaluation data (multiple evals):
     * SmartDrive Info Snapshot (stored SmartDrive info - S/N, version numbers)
     * Pre-trial questionnaire data (TBD)
     * Post-trial questionnaire data (TBD)
     * With SmartDrive Data:
        * number of pushes
        * total time
        * total distance
        * average cadence
     * Without SmartDrive Data:
        * number of pushes
        * total time
        * total distance
        * average cadence
 * Dealer / Rep:
   * Email
   * Name
   * Region
   * Phone Number
   * Registered SmartDrives:
     * Serial Number
     * Location
     * Firmware versions
     * History of use (times / locations / and trial data)

**Comment by bradmartin** [comment]
@finger563 - I know you said there isn't a hard set rule of conventions, but want to check on prop style. Do you prefer snake_case, camelCase, kebab-case, etc for naming things like `first_name`? I prefer `snake_case` so let me know if there is something the team prefers.

**Comment by finger563** [comment]
@bradmartin I like both `snake_case` and `camelCase` pretty equally so as long as we're consistently using the same convention I'm happy :)

**Comment by bradmartin** [comment]
@devondoebele @finger563  - with the workspace structure this >> 
<img width="264" alt="models" src="https://user-images.githubusercontent.com/6006148/37154833-df1a04f4-22a6-11e8-82b6-d75a01860004.png"> is where you'll want to define the classes/interfaces. Just make sure to export them in the index.ts so we can import in mobile/web as needed 👍 If `models` isn't the term we want to go with, feel free to change. Since those are just data structures we can share across any project, which is what `libs` is for (platform-agnostic code).

**Comment by finger563** [comment]
Now is the time for us to start collecting and sending these data into the collections i've added to Kinvey @bradmartin :) 

For now we just need to start stubbing out the structure and sending dummy data that is properly associated - i'm working on #33 which will start collecting some of the data.  We also need to tie the actual forms from the `Eval entry`, `training`, and `trial` into the collections / data to be sent.

**Comment by finger563** [comment]
Some of the remaining aspects of this feature are:

* logging demo unit use / handover between dealers and clinicians (#48)
* user data / roles (#34 )

**Comment by finger563** [comment]
These last two aspects (just above) are not needed for release version 1.0 of the app - this issue is being moved to the 1.1 milestone.

**Comment by finger563** [comment]
As of the most recent issues and updates this issue is now complete or replaced by the newer issues.
