### ISSUE TITLE
add text to OTA page telling user not to leave during OTA

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#316]
and letting them know that if they leave the OTAs will be cancelled.

**Comment by bradmartin** [comment]
Back pressed handled for android and swipe disabled for iOS. 

Will finish the navbutton for iOS and confirm the UX flow to wrap this up on Wednesday for final test build.

**Comment by finger563** [comment]
I think this is closed?

**Comment by bradmartin** [comment]
Yep, all good 🤑
