### ISSUE TITLE
iOS GIF size / scaling bugs

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#325]
as seen by the screenshot below, the GIF sizing doesn't work well on iOS across different screen sizes / aspect ratios:

![image](https://user-images.githubusercontent.com/213467/49751301-b0f33400-fc72-11e8-9e76-e615e5a6289a.png)

**Comment by bradmartin** [comment]
![simulator screen shot - ipad pro 12 9-inch 3rd generation - 2019-02-19 at 16 42 03](https://user-images.githubusercontent.com/6006148/53052826-54c44180-3465-11e9-8e68-79cc62f71420.png)

![simulator screen shot - iphone xr - 2019-02-19 at 16 42 00](https://user-images.githubusercontent.com/6006148/53052832-57bf3200-3465-11e9-8ce3-d9513c29924d.png)

**Comment by bradmartin** [comment]
![simulator screen shot - ipad pro 12 9-inch 3rd generation - 2019-02-19 at 16 41 52](https://user-images.githubusercontent.com/6006148/53052994-c9977b80-3465-11e9-96f6-8def9e1df8ad.png)
 iPad now ^
