### ISSUE TITLE
Add ability to register users as the different roles that have been created in Kinvey

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#34]

**Comment by finger563** [comment]
according to [this link](https://devcenter.kinvey.com/nativescript/guides/roles) the kinvey module we're using doesn't support roles - we have to use https://devcenter.kinvey.com/rest/guides/roles to manage the roles - we may need to auto-assign roles from the console?

**Comment by bradmartin** [comment]
Closing since we have user types established in the app now and on the `Users` collection.
