### ISSUE TITLE
Design and develop icons / splash screens

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#36]
We need app icons and splash screens (animations?) for the app

**Comment by bradmartin** [comment]
![launchscreen-center 2x](https://user-images.githubusercontent.com/6006148/42892264-058cfd34-8a77-11e8-860f-ceb7de79ba6f.png)
![icon](https://user-images.githubusercontent.com/6006148/42892265-05a62ca0-8a77-11e8-9cbc-d62af1c6c08d.png)

**Comment by bradmartin** [comment]
![launchscreen-center](https://user-images.githubusercontent.com/6006148/42892371-496d5a80-8a77-11e8-8bb5-3f2907d2f670.png)
