### ISSUE TITLE
Push Notifications from Kinvey

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#5]
EDIT: The specific push notifications have been moved to their own issues

**Comment by finger563** [comment]
Possibly blocked on https://github.com/Kinvey/nativescript-sdk/issues/28 - since I can't seem to get push notifications working otherwise, the collection hook code `onPostSave` is running fine with no issues and claims to be pushing to the users and working.

**Comment by finger563** [comment]
still blocked on https://github.com/Kinvey/nativescript-sdk/issues/28 unless @bradmartin  you know of a way around this issue

**Comment by bradmartin** [comment]
Looks like the `push` is in the root of the module and not in a sub directory. So

`import * as Kinvey from 'kinvey-nativescript-sdk';` and using `Kinvey.Push` will access the class and should work, haven't tested it yet though. Depends how the actual `push` source file is configured, but I assume it is exporting a `Push` class.

**Comment by bradmartin** [comment]
https://github.com/Kinvey/nativescript-sdk/issues/28#issuecomment-403683823 this is the fix - will see if they do it tomorrow or not. I'm testing the `register` method out now.

**Comment by finger563** [comment]
I'm assuming we're still waiting on a fix for `.register` failing for this to be completed?

**Comment by bradmartin** [comment]
Yes. I'll ping Brian Rinaldi (devrel for Kinvey at Progress) about this again and see if he can help bump it.

**Comment by finger563** [comment]
Now waiting on: https://github.com/Kinvey/nativescript-sdk/issues/39 to get data properly

**Comment by bradmartin** [comment]
Push works on both platforms now. We will need to generate the Distribution/Production certs for iOS when we do a release build 👍 but Kinvey push is working great.

**Comment by finger563** [comment]
Awesome @bradmartin - I think we can close this issue now since we have both platforms of Push Notification working?

**Comment by bradmartin** [comment]
yea except for the data issue you mentioned, which we can just open a newer issue with that for now 👍

**Comment by finger563** [comment]
awesome!
