### ISSUE TITLE
 fix styling for text in evaluation pages (eval entry and trial)

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#63]
some styling is messed up on ios

**Comment by devondoebele** [comment]
added .trial-recommendation to trial.comonent.ios.scss

not seeing any issues with eval entry? what specifically are you seeing?

**Comment by finger563** [comment]
the last part was the `other` descriptor text box that was missing styling in ios - i've fixed that now

**Comment by finger563** [comment]
closed by https://github.com/PushTracker/EvalApp/commit/3127e4ed14b818e3566bba0b72201d47c55e95a4

(the other fix in eval entry wasn't actually style - it was a mis-spelling of Quickie as Quckie)
