### ISSUE TITLE
add "up to date" label/badge to demo units that are up to date

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#64]
or conversely an "out of date" label to units that are out of date
- [x] ota page
- [ ] demo detail page
- [x] demo list page
- [ ] home page

**Comment by devondoebele** [comment]
I added the html but couldn't find the property to bind to it.

**Comment by finger563** [comment]
it's the demo's 3 version attributes - `pt_version`, `mcu_version`, and `ble_version` - but i'm adding a new method `isUpToDate(version: string): boolean` which will make our lives easier
