### ISSUE TITLE
Carousel in OTA page doesn't load properly on first load

### ISSUE THREAD

**Issue by devondoebele** [PushTracker/EvalApp#65]
At least in iOS. Need to test Android. Navigating away and back fixes the layout ¯\_(ツ)_/¯

**Comment by finger563** [comment]
Weird - on the iphone 7 i've got here it works just fine - does the title (firmware version) load and do the buttons show up or does it keep saying `fetching latest firmware data from the server`?

**Comment by finger563** [comment]
oh i see - this is after you changed it to be a carousel - i'll see how it works on android and if i can fix it :)

**Comment by finger563** [comment]
Cannot fix - cannot use `nativescript-carousel` with dynamic content
