### ISSUE TITLE
update video descriptions

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#72]
We should probably have 
`title`
`brief`
`detailed`

so that we can show title or brief on the home page and `title` and `detailed` on the videos page

**Comment by finger563** [comment]
these are now in `en.json` which are now hosted on the kinvey file store

**Comment by finger563** [comment]
we don't need to change the format now that we've changed how we show the videos (#164) - but we definitely need to make sure the video descriptions are updated so that they aren't written in first person (*cough* @devondoebele *cough*) ;)

**Comment by finger563** [comment]
@devondoebele let me know when this is done so that I can update the `en.json` on the server :)

**Comment by devondoebele** [comment]
So looking through these, I’m not sure we really need any changes other than:

"In this video, Chels and Steph are interviewed about many aspects of their lives, and how they have been impacted by SmartDrive”

Thoughts?

Devon Doebele
Permobil, Inc.
321.288.4066
devon.doebele@permobil.com

**Comment by finger563** [comment]
Probably need to remove the entry related to the PushTracker app entirely at the very least, but other than that I'll leave it up to your discretion.

**Comment by devondoebele** [comment]
But don’t we want people to have a resource on the PushTracker app?

Devon Doebele
Permobil, Inc.
321.288.4066
devon.doebele@permobil.com
