### ISSUE TITLE
In iOS Text from slides in OTA remain on screen when navigating back

### ISSUE THREAD

**Issue by devondoebele** [PushTracker/EvalApp#73]
@Brad, hoping your expertise will know what is causing this.

**Comment by finger563** [comment]
This has to do with the `setInterval` i added for automatically transitioning the pages - i think we need to make sure the element is completely dead before we route

**Comment by bradmartin** [comment]
@finger563 this one good after the update and the interval fix?

**Comment by finger563** [comment]
no this issue is still present - just navigate to the ota page, swipe once, then navigate back and you should see it

**Comment by bradmartin** [comment]
see branch https://github.com/PushTracker/EvalApp/tree/issue-73 for now - will clean up tomorrow and PR into master
