### ISSUE TITLE
In iOS a trial hangs in "Stopping Trial"

### ISSUE THREAD

**Issue by devondoebele** [PushTracker/EvalApp#74]
This occurred three times in a row. iOS 11.4 iPhone X. I was unable to successfully move forward.

**Comment by finger563** [comment]
Its only on the with smart drive trial iirc. Has to do with not receiving the data, iOS data reception is very slow. Disconnecting the pt and reconnecting it manually fixes it

**Comment by devondoebele** [comment]
Ok, I was able to make it through a trial. I got a push count of 14 with SmartDrive and 0 w/o. I only did taps for the w/ SmartDrive phase, and simulated natural pushes, brushing my leg, in the w/o phase. Shouldn't those been counted?

**Comment by finger563** [comment]
this is similar to #61 - they're the same bug fundamentally but sometimes it appears to not receive the `MotorDistance` data and so it either hangs or you have to manually disconnect and reconnect the PT
