### ISSUE TITLE
update default pictures of SD / PT in demo-details page

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#95]
right now the SD in particular needs fixing

**Comment by bradmartin** [comment]
@ken-max @finger563 - do we have the updated images already for this? Ken, if you have any questions on what ia
![pushtrackerfull](https://user-images.githubusercontent.com/6006148/43543881-eeab6454-9596-11e8-8d51-19227a412700.png)
![smartdrivefull](https://user-images.githubusercontent.com/6006148/43543882-eebfbd00-9596-11e8-8ec7-a817e6806d2a.png)

Looks like these are the two images being used on this page @finger563

**Comment by bradmartin** [comment]
![sd-top-1](https://user-images.githubusercontent.com/6006148/43545217-e6867bb6-959a-11e8-8bed-da113dbda3e8.png)
per Devon ^
